# Generated by Django 3.2.7 on 2021-09-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название категории картинок')),
                ('description', models.CharField(default=None, max_length=250, verbose_name='Описание категории картинок')),
            ],
            options={
                'verbose_name': 'Категория картинок',
                'verbose_name_plural': 'Категории картинок',
            },
        ),
        migrations.CreateModel(
            name='ImageChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название раздела картинок')),
                ('description', models.CharField(default=None, max_length=250, verbose_name='Описание раздела картинок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.imagecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Раздел картинок',
                'verbose_name_plural': 'Разделы картинок',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название картинки')),
                ('description', models.CharField(default=None, max_length=250, verbose_name='Описание картинки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.imagechapter', verbose_name='Раздел картинки')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
