# Generated by Django 3.2.7 on 2021-09-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210910_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название темы конспектов')),
                ('description', models.CharField(default=None, max_length=250, verbose_name='Описание темы конспектов')),
            ],
            options={
                'verbose_name': 'Категория конспекта',
                'verbose_name_plural': 'Категории конспектов',
            },
        ),
        migrations.AlterModelOptions(
            name='abstract',
            options={'verbose_name': 'Конспект', 'verbose_name_plural': 'Конспекты'},
        ),
        migrations.RemoveField(
            model_name='abstract',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='abstract',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='abstract',
            name='image_3',
        ),
        migrations.AddField(
            model_name='abstract',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='abstract/', verbose_name='Картинка по желанию'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='text',
            field=models.TextField(default=None, verbose_name='Текст Конспекта'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание Конспекта'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.abstractcategory', verbose_name='Тема конспекта'),
        ),
    ]
