# Generated by Django 3.2.7 on 2021-09-15 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210911_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapbook',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='lapbook',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='lapbook',
            name='image_3',
        ),
        migrations.CreateModel(
            name='LapbookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='lapbook/', verbose_name='Картинка 1')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lapbook')),
            ],
        ),
    ]
