# Generated by Django 3.2.7 on 2021-09-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210915_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapbookimage',
            name='image',
            field=models.FileField(blank=True, upload_to='lapbook/', verbose_name='Картинка'),
        ),
        migrations.RemoveField(
            model_name='lapbookimage',
            name='task',
        ),
        migrations.AddField(
            model_name='lapbookimage',
            name='task',
            field=models.ManyToManyField(to='main.Lapbook'),
        ),
    ]
