# Generated by Django 3.2.7 on 2021-09-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_lapbook_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapbookimage',
            name='task',
        ),
        migrations.AddField(
            model_name='lapbookimage',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.lapbook'),
        ),
    ]
