# Generated by Django 3.2.7 on 2021-09-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210915_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lapbookimage',
            options={'verbose_name': 'Лэпбук фото', 'verbose_name_plural': 'Лэпбуки фото'},
        ),
        migrations.CreateModel(
            name='AbstractImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='abstract/', verbose_name='Картинка')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.abstract')),
            ],
            options={
                'verbose_name': 'Конспект фото',
                'verbose_name_plural': 'Конспекты фото',
            },
        ),
    ]
