# Generated by Django 3.2.7 on 2021-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210916_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='Описание Конспекта'),
        ),
    ]
