# Generated by Django 3.2.7 on 2021-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_abstract_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='text',
            field=models.TextField(default=None, null=True, verbose_name='Текст Конспекта'),
        ),
    ]
