# Generated by Django 3.2.7 on 2021-09-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_abstract_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='image',
        ),
        migrations.AddField(
            model_name='abstract',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='user_fio',
            field=models.CharField(default=None, max_length=250, verbose_name='ФИО автора'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='user_image',
            field=models.ImageField(default=None, null=True, upload_to='abstract_user/', verbose_name='Фото профиля создателя'),
        ),
    ]
