# Generated by Django 3.2.7 on 2021-09-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210916_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='user_fio',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='ФИО автора'),
        ),
    ]
