# Generated by Django 3.2.7 on 2021-09-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_development_developmentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название конкурса')),
                ('description', models.TextField(default=None, null=True, verbose_name='Описание конкурса')),
                ('text', models.TextField(default=None, null=True, verbose_name='Текст конкурса')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
            },
        ),
        migrations.CreateModel(
            name='ContestsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='contests/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Конкурс фото',
                'verbose_name_plural': 'Конкурсы фото',
            },
        ),
        migrations.CreateModel(
            name='Crafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название поделок')),
                ('description', models.TextField(default=None, null=True, verbose_name='Описание поделок')),
                ('text', models.TextField(default=None, null=True, verbose_name='Текст поделок')),
                ('user_fio', models.CharField(default=None, max_length=250, null=True, verbose_name='ФИО автора')),
                ('user_image', models.CharField(default=None, max_length=250, null=True, verbose_name='Ссылка на аватар автора')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Поделка',
                'verbose_name_plural': 'Поделки',
            },
        ),
        migrations.CreateModel(
            name='CraftsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название темы поделок')),
                ('description', models.CharField(default=None, max_length=250, verbose_name='Описание темы поделок')),
            ],
            options={
                'verbose_name': 'Категория поделки',
                'verbose_name_plural': 'Категории поделок',
            },
        ),
        migrations.CreateModel(
            name='CraftsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='crafts/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Поделка фото',
                'verbose_name_plural': 'Поделки фото',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название темы разработки')),
                ('description', models.CharField(default=None, max_length=250, verbose_name='Описание темы разработки')),
            ],
            options={
                'verbose_name': 'Категория разработки',
                'verbose_name_plural': 'Категории разработки',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название игры')),
                ('description', models.TextField(default=None, null=True, verbose_name='Описание игры')),
                ('text', models.TextField(default=None, null=True, verbose_name='Текст игры')),
                ('user_fio', models.CharField(default=None, max_length=250, null=True, verbose_name='ФИО автора')),
                ('user_image', models.CharField(default=None, max_length=250, null=True, verbose_name='Ссылка на аватар автора')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GamesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название темы игр')),
                ('description', models.CharField(default=None, max_length=250, verbose_name='Описание темы игр')),
            ],
            options={
                'verbose_name': 'Категория игры',
                'verbose_name_plural': 'Категории игр',
            },
        ),
        migrations.CreateModel(
            name='GamesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='games/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Игра фото',
                'verbose_name_plural': 'Игры фото',
            },
        ),
        migrations.CreateModel(
            name='HolidayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='holiday/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Праздник фото',
                'verbose_name_plural': 'праздники фото',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название оформления')),
                ('description', models.TextField(default=None, null=True, verbose_name='Описание оформления')),
                ('text', models.TextField(default=None, null=True, verbose_name='Текст оформления')),
                ('user_fio', models.CharField(default=None, max_length=250, null=True, verbose_name='ФИО автора')),
                ('user_image', models.CharField(default=None, max_length=250, null=True, verbose_name='Ссылка на аватар автора')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Оформление',
                'verbose_name_plural': 'Оформления',
            },
        ),
        migrations.CreateModel(
            name='RegistrationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Название темы оформления')),
                ('description', models.CharField(default=None, max_length=250, verbose_name='Описание темы оформления')),
            ],
            options={
                'verbose_name': 'Категория оформления',
                'verbose_name_plural': 'Категории оформления',
            },
        ),
        migrations.CreateModel(
            name='RegistrationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='registration/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Оформление фото',
                'verbose_name_plural': 'Оформление фото',
            },
        ),
        migrations.AlterModelOptions(
            name='development',
            options={'verbose_name': 'Разработка', 'verbose_name_plural': 'Разработки'},
        ),
        migrations.AlterModelOptions(
            name='developmentimage',
            options={'verbose_name': 'Разработка фото', 'verbose_name_plural': 'Разработки фото'},
        ),
        migrations.AlterField(
            model_name='abstract',
            name='user_image',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Ссылка на аватар автора'),
        ),
        migrations.AlterField(
            model_name='development',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='Описание разработки'),
        ),
        migrations.AlterField(
            model_name='development',
            name='name',
            field=models.CharField(default=None, max_length=250, verbose_name='Название разработки'),
        ),
        migrations.AlterField(
            model_name='development',
            name='text',
            field=models.TextField(default=None, null=True, verbose_name='Текст разработки'),
        ),
        migrations.AlterField(
            model_name='development',
            name='user_image',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Ссылка на аватар автора'),
        ),
        migrations.AlterField(
            model_name='developmentimage',
            name='image',
            field=models.FileField(blank=True, upload_to='development/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='developmentimage',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.development'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='theme',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.holidaycategory', verbose_name='Тема праздника'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='user_image',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Ссылка на аватар автора'),
        ),
        migrations.DeleteModel(
            name='HolidaytImage',
        ),
        migrations.AddField(
            model_name='registrationimage',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.development'),
        ),
        migrations.AddField(
            model_name='registration',
            name='theme',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.registrationcategory', verbose_name='Тема оформления'),
        ),
        migrations.AddField(
            model_name='holidayimage',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.holiday'),
        ),
        migrations.AddField(
            model_name='gamesimage',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.development'),
        ),
        migrations.AddField(
            model_name='games',
            name='theme',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gamescategory', verbose_name='Тема игры'),
        ),
        migrations.AddField(
            model_name='craftsimage',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.development'),
        ),
        migrations.AddField(
            model_name='crafts',
            name='theme',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.craftscategory', verbose_name='Тема поделок'),
        ),
        migrations.AddField(
            model_name='contestsimage',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.development'),
        ),
        migrations.AlterField(
            model_name='development',
            name='theme',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.developmentcategory', verbose_name='Тема разработки'),
        ),
    ]
