# Generated by Django 3.2.7 on 2021-09-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_reviews_contests'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='user_fio',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='ФИО автора'),
        ),
        migrations.AddField(
            model_name='contests',
            name='user_image',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Ссылка на аватар автора'),
        ),
        migrations.AlterField(
            model_name='contestsimage',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.contests'),
        ),
    ]
