# Generated by Django 3.2.7 on 2021-09-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210920_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='likes',
        ),
    ]
