# Generated by Django 3.2.7 on 2021-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_contests_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Колличество лайков'),
        ),
    ]
