# Generated by Django 3.2.7 on 2021-09-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210920_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews_contests',
            options={'verbose_name': 'Конкурс комментарий', 'verbose_name_plural': 'Конкурсы комментарии'},
        ),
        migrations.CreateModel(
            name='Reviews_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=5000, verbose_name='USER NAME')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('user_photo', models.CharField(max_length=500, verbose_name='Ссылка на фото ')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.registration', verbose_name='Оформление')),
            ],
            options={
                'verbose_name': 'Оформление комментарий',
                'verbose_name_plural': 'Оформление комментарий',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Lapbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=5000, verbose_name='USER NAME')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('user_photo', models.CharField(max_length=500, verbose_name='Ссылка на фото ')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lapbook', verbose_name='Лэпбук')),
            ],
            options={
                'verbose_name': 'Лэпбук комментарий',
                'verbose_name_plural': 'Лэпбук комментарий',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=5000, verbose_name='USER NAME')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('user_photo', models.CharField(max_length=500, verbose_name='Ссылка на фото ')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка комментарий',
                'verbose_name_plural': 'Картинка комментарий',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=5000, verbose_name='USER NAME')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('user_photo', models.CharField(max_length=500, verbose_name='Ссылка на фото ')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.holiday', verbose_name='Праздник')),
            ],
            options={
                'verbose_name': 'Праздник комментарий',
                'verbose_name_plural': 'Праздник комментарий',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=5000, verbose_name='USER NAME')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('user_photo', models.CharField(max_length=500, verbose_name='Ссылка на фото ')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.games', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Игры комментарий',
                'verbose_name_plural': 'Игры комментарии',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=5000, verbose_name='USER NAME')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('user_photo', models.CharField(max_length=500, verbose_name='Ссылка на фото ')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.development', verbose_name='Разработка')),
            ],
            options={
                'verbose_name': 'Разработки комментарий',
                'verbose_name_plural': 'Разработки комментарий',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Crafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=5000, verbose_name='USER NAME')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('user_photo', models.CharField(max_length=500, verbose_name='Ссылка на фото ')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.crafts', verbose_name='Поделка')),
            ],
            options={
                'verbose_name': 'Комментарий Поделка',
                'verbose_name_plural': 'Комментарий Поделка',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=5000, verbose_name='USER NAME')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('user_photo', models.CharField(max_length=500, verbose_name='Ссылка на фото ')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.abstract', verbose_name='Конспект')),
            ],
            options={
                'verbose_name': 'Конспект комментарий',
                'verbose_name_plural': 'Конспект комментарий',
            },
        ),
    ]
